# Generated by Django 5.0.6 on 2024-06-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Course title')),
                ('description', models.TextField(verbose_name='Course description')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Course image')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Course title')),
                ('description', models.TextField(verbose_name='Course description')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Course image')),
                ('link', models.TextField(verbose_name='Lesson link')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
    ]
